<?php
/* Configurations for US - Healthy Hearing */
return [
    'International' => [
        'country' => 'US',
    ],
    'siteName' => 'Healthy Hearing',
    'siteNameAbbr' => 'HH',
    'siteUrl' => 'HealthyHearing.com',
    'sitemapGenUrl' => 'www1.healthyhearing.com',
    'logo' => '/img/hh-logo.svg',
    'map' => '/img/us-map.svg',
    'heroHeadline' => '<em>Be part of the </em><br />conversation',
    'countryName' => 'the US',
    'fullCountryName' => 'the United States',
    'stateLabel' => 'state',
    'zipLabel' => 'ZIP code',
    'zipShort' => 'ZIP',
    'phone' => '(800) 567-1692',
    'checkPayment' => 'Check',
    'errorPageTitle' => 'Page not found',
    'roughClinicCount' => 'thousands',
    'roughProviderCount' => 'over 4,000',
    'isLoadBalanced' => true,
    'regionalSpelling' => [
        'center' => 'center',
    ],
    // Social media
    'twitterHandle' => '@hearingaids',
    'twitterCard' => 'summary_large_image',
    'ogSiteName' => 'Healthy Hearing',
    'ogLocale' => 'en_US',
    'sameAsSocialLinks' => [
        'facebook' => 'https://www.facebook.com/healthyhearing',
        'twitter' => 'https://twitter.com/HearingAids',
        'youtube' => 'https://www.youtube.com/user/HealthyHearing',
        'linkedIn' => 'https://www.linkedin.com/company/9426778',
    ],
    // From email address
    'email' => ['contacthh@healthyhearing.com' => 'Healthy Hearing'],
    'customer-support-email' => 'contacthh@healthyhearing.com',
    // Page and content-type flags
    'showReports' => true,
    'showManufacturers' => true,
    'showAssistiveListening' => true,
    'showTinnitus' => true,
    'showNewsletter' => true,
    'showHearingTest' => true,
    'showFeeds' => true,
    'showAds' => true,
    'showReviewsByCity' => true,
    // Provider Variables
    'showProviderLicenses' => false, // Hide provider licenses
    'showProviderCredentialButtons' => true,
    'showProviderNpi' => true,
    'showProviderAudOrHis' => true,
    // Call Tracking
    'isCallSourceGenerationEnabled' => true,
    'isCallAssistEnabled' => true,
    'isCallTrackingEnabled' => false,
    'isLeadscoreEnabled' => false,
    'isIvrEnabled' => false,
    'callSourceLocalHub' => null,
    'callSourceAdSource' => 'healthyhearing.com',
    'allowTollCharges' => true,
    'postAdfTargetNumber' => '7325074800',
    'quickPickNumber' => '1-877-872-7165',
    // Imports
    'import-email' => [
        'contacthh@healthyhearing.com',
        'it@healthyhearing.com',
    ],
    'isYhnImportEnabled' => true,
    'isOticonImportEnabled' => true,
    'isCqpImportEnabled' => true,
    'isTieringEnabled' => true,
    'isYhnAutoMatched' => false,
    'importTag' => 'YHN',
    // Misc
    'clinicMaxRange' => '60',
    'htmlLanguage' => 'en-US',
    'isMetric' => false, // Displays distance in miles
    'isSitemapPingEnabled' => true,
    'allowCopySitemaps' => true,
    'showImageSitemap' => true,
    'isCrmEmailEnabled' => true,
    'isVwoEnabled' => true,
    // Paid features
    'isOpenClosedEnabled' => true,
    'showSocialMediaContentLibrary' => true,
    // Location CSV export fields and non-US overrides
    'locationExportFields' => [
        'id',
        'oticon_id',
        'title',
        'address',
        'address_2',
        'city',
        'state',
        'zip',
        'phone',
        'email',
        'url',
        'facebook',
        'twitter',
        'youtube',
        'created',
        'modified',
        'is_listing_type_frozen',
        'frozen_expiration',
        'oticon_tier',
        'listing_type',
        'is_active',
        'is_show',
        'is_grace_period',
        'grace_period_end',
        'average_rating',
        'reviews_approved',
        'last_review_date',
        'priority',
        'completeness',
        'last_import_status',
        'LocationUser.email',
        'LocationUser.username',
        'LocationUser.clinic_password',
        'LocationUser.lastlogin',
        'location_segment',
        'entity_segment',
        'yhn_location_id',
        'is_yhn',
        'is_oticon',
        'is_retail',
        'is_hh',
        'direct_book_type',
        'is_service_agreement_signed',
    ],
];
