<?php
/* Configurations for Canada - Hearing Directory */
return [
    'siteName' => 'Hearing Directory',
    'siteNameAbbr' => 'HD',
    'siteUrl' => 'HearingDirectory.ca',
    'logo' => '/img/hearing-directory.svg',
    'map' => '/img/ca-map.svg',
    'heroHeadline' => 'Find a hearing specialist now',
    'countryName' => 'Canada',
    'fullCountryName' => 'Canada',
    'stateLabel' => 'province',
    'zipLabel' => 'Postal code',
    'zipShort' => 'postal code',
    'phone' => '(888) 621-8058',
    'checkPayment' => 'Cheque',
    'errorPageTitle' => 'Page not found',
    'roughClinicCount' => 'hundreds',
    'roughProviderCount' => 'hundreds of',
    'isLoadBalanced' => false,
    'regionalSpelling' => [
        'center' => 'centre',
    ],
    // Social Media
    'twitterHandle' => '@HearingaidsCAN',
    'twitterCard' => 'summary_large_image',
    'ogSiteName' => 'Hearing Directory',
    'ogLocale' => 'en_CA',
    'sameAsSocialLinks' => [
        'facebook' => 'https://www.facebook.com/HearingDirectoryCANADA',
        'twitter' => 'https://x.com/HearingaidsCAN',
    ],
    // Google tag manager
    'gtmId' => 'GTM-TC3K3WL',
    // Google Maps API - Development project
    'GoogleMaps' => [
        'MapsJsApiKey' => 'AIzaSyCKrxAOnAWOJkqV1qn3vVz7fUfzrQnNemE',
        'MapsStaticApiKey' => 'AIzaSyA19OSEZ1mrfA4-ReJ3zK_iOsp_gXXhpTo',
        'WebServicesApiKey' => 'AIzaSyD4eNrfxMTwBPEVAXdhZKMgfVaCdXt8GDQ',
    ],
    // From email address
    'email' => ['contacthd@hearingdirectory.ca' => 'Hearing Directory'],
    'customer-support-email' => 'contacthd@hearingdirectory.ca',
    // Page and content-type flags
    'showReports' => false,
    'showManufacturers' => false,
    'showAssistiveListening' => false,
    'showTinnitus' => false,
    'showNewsletter' => false,
    'showHearingTest' => true,
    'showFeeds' => false,
    'showAds' => false,
    'showReviewsByCity' => false,
    // Provider Variables
    'showProviderCredentialButtons' => false,
    'showProviderAudOrHis' => false,
    // Call Tracking
    'isCallSourceGenerationEnabled' => true,
    'isCallAssistEnabled' => false,
    'isCallTrackingEnabled' => true,
    'isLeadscoreEnabled' => true,
    'isIvrEnabled' => false,
    'callSourcePrefix' => 'HDCA-',
    'callSourceLocalHub' => 'Local - Canada numbers',
    'callSourceAdSource' => 'hearingdirectory.ca',
    'allowTollCharges' => false,
    'postAdfTargetNumber' => null,
    'quickPickNumber' => null,
    // Imports
    'import-email' => [
        'contacthd@hearingdirectory.ca',
        'it@hearingdirectory.ca',
    ],
    'isYhnImportEnabled' => false,
    'isOticonImportEnabled' => false,
    'isCqpImportEnabled' => false,
    'isTieringEnabled' => false,
    'importTag' => 'IMP',
    // Misc
    'clinicMaxRange' => '40',
    'htmlLanguage' => 'en-CA',
    'isMetric' => true, // Displays distance in km
    'isCrmEmailEnabled' => false,
    'isVwoEnabled' => false,
    // Paid features
    'isOpenClosedEnabled' => true,
    'showSocialMediaContentLibrary' => false,
    // Location CSV export fields and non-US overrides
    'locationExportFields' => [
        'id',
        'id_oticon',
        'title',
        'address',
        'address_2',
        'city',
        'state',
        'zip',
        'phone',
        'email',
        'url',
        'facebook',
        'twitter',
        'youtube',
        'created',
        'modified',
        'is_active',
        'is_show',
        'average_rating',
        'reviews_approved',
        'last_review_date',
        'priority',
        'completeness',
        'LocationUser.email',
        'LocationUser.username',
        'LocationUser.clinic_password',
        'LocationUser.lastlogin',
        'is_oticon',
        'is_retail',
    ],
    'locationExportFieldOverrides' => [
        'state' => 'province',
        'zip' => 'postal_code',
        'hh_url' => 'hd_url',
        'hh_username' => 'hd_username',
    ],
    'reviewExportFieldOverrides' => [
        'zip' => 'postal_code',
        'hh_url' => 'hd_url',
    ],
    'Sitemap.tables' => [
        'Main',
        'City',
        'Help',
        'Clinic',
        'State',
    ],
    'Sitemap.tableAliases' => [
        'City' => 'Cities',
        'Help' => 'Wikis',
        'Clinic' => 'Locations',
        'State' => 'States',
    ],
    'states' => [
        'AB' => 'Alberta',
        'BC' => 'British Columbia',
        'MB' => 'Manitoba',
        'NB' => 'New Brunswick',
        'NL' => 'Newfoundland and Labrador',
        'NT' => 'Northwest Territories',
        'NS' => 'Nova Scotia',
        'NU' => 'Nunavut',
        'ON' => 'Ontario',
        'PE' => 'Prince Edward Island',
        'QC' => 'Quebec',
        'SK' => 'Saskatchewan',
        'YT' => 'Yukon',
    ],
    'regions' => [
    ],
];
