<?php
/* Configurations for Canada - Hearing Directory */
return [
    'International' => [
        'country' => 'CA',
    ],
    'siteName' => 'Hearing Directory',
    'siteNameAbbr' => 'HD',
    'siteUrl' => 'HearingDirectory.ca',
    'logo' => '/img/hearing-directory.svg',
    'map' => '/img/ca-map.svg',
    'heroHeadline' => '<em>Be part of the </em><br />conversation',
    'countryName' => 'Canada',
    'fullCountryName' => 'Canada',
    'stateLabel' => 'province',
    'zipLabel' => 'postal code',
    'zipShort' => 'postal code',
    'phone' => '(888) 621-8058',
    'checkPayment' => 'Cheque',
    'errorPageTitle' => 'Page not found',
    'roughClinicCount' => 'hundreds',
    'roughProviderCount' => 'hundreds of',
    'isLoadBalanced' => false,
    'regionalSpelling' => [
        'center' => 'centre',
    ],
    // Social Media
    'twitterHandle' => '@HearingaidsCAN',
    'twitterCard' => 'summary_large_image',
    'ogSiteName' => 'Hearing Directory',
    'ogLocale' => 'en_CA',
    'sameAsSocialLinks' => [
        'facebook' => 'https://www.facebook.com/HearingDirectoryCANADA',
        'twitter' => 'https://twitter.com/HearingaidsCAN',
    ],
    // From email address
    'email' => ['contacthd@hearingdirectory.ca' => 'Hearing Directory'],
    'customer-support-email' => 'contacthd@hearingdirectory.ca',
    // Page and content-type flags
    'showReports' => false,
    'showManufacturers' => false,
    'showAssistiveListening' => false,
    'showTinnitus' => false,
    'showNewsletter' => false,
    'showHearingTest' => true,
    'showFeeds' => false,
    'showAds' => false,
    'showReviewsByCity' => false,
    // Provider Variables
    'showProviderLicenses' => false,
    'showProviderCredentialButtons' => false,
    'showProviderNpi' => false,
    'showProviderAudOrHis' => false,
    // Call Tracking
    'isCallSourceGenerationEnabled' => true,
    'isCallAssistEnabled' => false,
    'isCallTrackingEnabled' => true,
    'isLeadscoreEnabled' => true,
    'isIvrEnabled' => false,
    'callSourcePrefix' => 'HDCA-',
    'callSourceLocalHub' => 'Local - Canada numbers',
    'callSourceAdSource' => 'hearingdirectory.ca',
    'allowTollCharges' => false,
    'postAdfTargetNumber' => null,
    'quickPickNumber' => null,
    // Imports
    'import-email' => [
        'contacthd@hearingdirectory.ca',
        'it@hearingdirectory.ca',
    ],
    'isYhnImportEnabled' => false,
    'isOticonImportEnabled' => false,
    'isCqpImportEnabled' => false,
    'isTieringEnabled' => false,
    'importTag' => 'IMP',
    // Misc
    'clinicMaxRange' => '40',
    'htmlLanguage' => 'en-CA',
    'isMetric' => true, // Displays distance in km
    'isSitemapPingEnabled' => true,
    'allowCopySitemaps' => false,
    'showImageSitemap' => false,
    'isCrmEmailEnabled' => false,
    'isVwoEnabled' => false,
    // Paid features
    'isOpenClosedEnabled' => true,
    'showSocialMediaContentLibrary' => false,
    // Location CSV export fields and non-US overrides
    'locationExportFields' => [
        'id',
        'oticon_id',
        'title',
        'address',
        'address_2',
        'city',
        'state',
        'zip',
        'phone',
        'email',
        'url',
        'facebook',
        'twitter',
        'youtube',
        'created',
        'modified',
        'is_active',
        'is_show',
        'average_rating',
        'reviews_approved',
        'last_review_date',
        'priority',
        'completeness',
        'LocationUser.email',
        'LocationUser.username',
        'LocationUser.clinic_password',
        'LocationUser.lastlogin',
        'is_oticon',
        'is_retail',
    ],
    'locationExportFieldOverrides' => [
        'state' => 'province',
        'zip' => 'postal_code',
        'hh_url' => 'hd_url',
        'hh_username' => 'hd_username',
    ],
    'reviewExportFieldOverrides' => [
        'zip' => 'postal_code',
        'hh_url' => 'hd_url',
    ],
];
