<?php
/* Configurations for US - Healthy Hearing */
return [
    'siteName' => 'Healthy Hearing',
    'siteNameAbbr' => 'HH',
    'siteUrl' => 'HealthyHearing.com',
    'sitemapGenUrl' => 'www1.healthyhearing.com',
    'logo' => '/img/hh-logo.svg',
    'map' => '/img/us-map.svg',
    'heroHeadline' => 'Find a hearing specialist now',
    'countryName' => 'the US',
    'fullCountryName' => 'the United States',
    'stateLabel' => 'state',
    'zipLabel' => 'ZIP code',
    'zipShort' => 'ZIP',
    'phone' => '(800) 567-1692',
    'checkPayment' => 'Check',
    'errorPageTitle' => 'Page not found',
    'roughClinicCount' => 'thousands',
    'roughProviderCount' => 'over 4,000',
    'isLoadBalanced' => true,
    'regionalSpelling' => [
        'center' => 'center',
    ],
    // Social media
    'twitterHandle' => '@hearingaids',
    'twitterCard' => 'summary_large_image',
    'ogSiteName' => 'Healthy Hearing',
    'ogLocale' => 'en_US',
    'sameAsSocialLinks' => [
        'facebook' => 'https://www.facebook.com/healthyhearing',
        'twitter' => 'https://x.com/HearingAids',
        'youtube' => 'https://www.youtube.com/user/HealthyHearing',
        'linkedIn' => 'https://www.linkedin.com/company/9426778',
    ],
    // From email address
    'email' => ['contacthh@healthyhearing.com' => 'Healthy Hearing'],
    'customer-support-email' => 'contacthh@healthyhearing.com',
    // Page and content-type flags
    'showReports' => true,
    'showManufacturers' => true,
    'showAssistiveListening' => true,
    'showTinnitus' => true,
    'showNewsletter' => true,
    'showHearingTest' => true,
    'showFeeds' => true,
    'showAds' => true,
    'showReviewsByCity' => true,
    // Provider Variables
    'showProviderCredentialButtons' => true,
    'showProviderAudOrHis' => true,
    // Call Tracking
    'isCallSourceGenerationEnabled' => true,
    'isCallAssistEnabled' => true,
    'isCallTrackingEnabled' => false,
    'isLeadscoreEnabled' => false,
    'isIvrEnabled' => false,
    'callSourceLocalHub' => null,
    'callSourceAdSource' => 'healthyhearing.com',
    'allowTollCharges' => true,
    'postAdfTargetNumber' => '7325074800',
    'quickPickNumber' => '1-877-872-7165',
    // Imports
    'import-email' => [
        'contacthh@healthyhearing.com',
        'it@healthyhearing.com',
    ],
    'isYhnImportEnabled' => true,
    'isOticonImportEnabled' => true,
    'isCqpImportEnabled' => true,
    'isTieringEnabled' => true,
    'isYhnAutoMatched' => false,
    'importTag' => 'YHN',
    // Google tag manager
    'gtmId' => 'GTM-P2V6GQ',
    // Google Maps API - Development project
    'GoogleMaps' => [
        'MapsJsApiKey' => 'AIzaSyCKrxAOnAWOJkqV1qn3vVz7fUfzrQnNemE',
        'MapsStaticApiKey' => 'AIzaSyA19OSEZ1mrfA4-ReJ3zK_iOsp_gXXhpTo',
        'WebServicesApiKey' => 'AIzaSyD4eNrfxMTwBPEVAXdhZKMgfVaCdXt8GDQ',
    ],
    // Misc
    'clinicMaxRange' => '60',
    'htmlLanguage' => 'en-US',
    'isMetric' => false, // Displays distance in miles
    'isCrmEmailEnabled' => true,
    'isVwoEnabled' => true,
    // Paid features
    'isOpenClosedEnabled' => true,
    'showSocialMediaContentLibrary' => true,
    // Location CSV export fields and non-US overrides
    'locationExportFields' => [
        'id',
        'id_oticon',
        'title',
        'address',
        'address_2',
        'city',
        'state',
        'zip',
        'phone',
        'email',
        'url',
        'facebook',
        'twitter',
        'youtube',
        'created',
        'modified',
        'is_listing_type_frozen',
        'frozen_expiration',
        'oticon_tier',
        'listing_type',
        'is_active',
        'is_show',
        'is_grace_period',
        'grace_period_end',
        'average_rating',
        'reviews_approved',
        'last_review_date',
        'priority',
        'completeness',
        'last_import_status',
        'LocationUser.email',
        'LocationUser.username',
        'LocationUser.clinic_password',
        'LocationUser.lastlogin',
        'location_segment',
        'entity_segment',
        'id_yhn_location',
        'is_yhn',
        'is_oticon',
        'is_retail',
        'is_hh',
        'direct_book_type',
        'is_service_agreement_signed',
    ],
    'Sitemap.tables' => [
        'Main',
        'City',
        'Help',
        'Content',
        'Clinic',
        'Corp',
        'State',
    ],
    'Sitemap.tableAliases' => [
        'City' => 'Cities',
        'Help' => 'Wikis',
        'Content' => 'Content',
        'Clinic' => 'Locations',
        'Corp' => 'Corps',
        'State' => 'States',
    ],
    'states' => [
        'AK' => 'Alaska',
        'AL' => 'Alabama',
        'AR' => 'Arkansas',
        'AZ' => 'Arizona',
        'CA' => 'California',
        'CO' => 'Colorado',
        'CT' => 'Connecticut',
        'DC' => 'Dist. of Columbia',
        'DE' => 'Delaware',
        'FL' => 'Florida',
        'GA' => 'Georgia',
        'HI' => 'Hawaii',
        'IA' => 'Iowa',
        'ID' => 'Idaho',
        'IL' => 'Illinois',
        'IN' => 'Indiana',
        'KS' => 'Kansas',
        'KY' => 'Kentucky',
        'LA' => 'Louisiana',
        'MA' => 'Massachusetts',
        'MD' => 'Maryland',
        'ME' => 'Maine',
        'MI' => 'Michigan',
        'MN' => 'Minnesota',
        'MO' => 'Missouri',
        'MS' => 'Mississippi',
        'MT' => 'Montana',
        'NC' => 'North Carolina',
        'ND' => 'North Dakota',
        'NE' => 'Nebraska',
        'NH' => 'New Hampshire',
        'NJ' => 'New Jersey',
        'NM' => 'New Mexico',
        'NV' => 'Nevada',
        'NY' => 'New York',
        'OH' => 'Ohio',
        'OK' => 'Oklahoma',
        'OR' => 'Oregon',
        'PA' => 'Pennsylvania',
        'RI' => 'Rhode Island',
        'SC' => 'South Carolina',
        'SD' => 'South Dakota',
        'TN' => 'Tennessee',
        'TX' => 'Texas',
        'UT' => 'Utah',
        'VA' => 'Virginia',
        'VT' => 'Vermont',
        'WA' => 'Washington',
        'WI' => 'Wisconsin',
        'WV' => 'West Virginia',
        'WY' => 'Wyoming',
    ],
    'regions' => [
        'Northeast' => array('MA', 'RI', 'CT', 'ME', 'NH', 'VT'),
        'MidAtlantic' => array('WV', 'PA', 'NJ', 'NY'),
        'Southeast' => array('TX', 'LA', 'MS', 'TN', 'AL', 'KY', 'NC', 'SC', 'FL', 'GA', 'MD', 'DE', 'VA', 'VI', 'PR', 'DC'),
        'Midwest' => array('NE', 'IA', 'OK', 'MO', 'MI', 'OH', 'IL', 'WI', 'MN', 'ND', 'SD', 'AR', 'KS', 'NE'),
        'West' => array('AK', 'WA', 'ID', 'UT', 'NV', 'WY', 'CO', 'NM', 'MT', 'OR', 'CA', 'AZ', 'HI'),
    ],
];
