// globals.d.ts
interface Window {
    PROSPECT_YES: string;
    PROSPECT_NO: string;
    PROSPECT_UNKNOWN: string;
    PROSPECT_DISCONNECTED: string;
    prospectTopics: Record<string, string>;
    SCORE_APPT_SET: string;
    SCORE_TENTATIVE_APPT: string;
    SCORE_APPT_SET_DIRECT: string;
    SCORE_NOT_REACHED: string;
    SCORE_MISSED_OPPORTUNITY: string;
    SCORE_DISCONNECTED: string;
    callTypes: Record<string, string>;
    CALL_TYPE_INBOUND: string;
    CALL_TYPE_INBOUND_QUICK_PICK: string;
    CALL_TYPE_VM_CALLBACK_CLINIC: string;
    CALL_TYPE_VM_CALLBACK_CONSUMER: string;
    CALL_TYPE_VM_CALLBACK_INVALID: string;
    CALL_TYPE_FOLLOWUP_APPT_REQUEST: string;
    CALL_TYPE_FOLLOWUP_APPT_REQUEST_DIRECT: string;
    CALL_TYPE_FOLLOWUP_APPT: string;
    CALL_TYPE_FOLLOWUP_NO_ANSWER: string;
    CALL_TYPE_FOLLOWUP_TENTATIVE_APPT: string;
    statuses: Record<string, string>;
    STATUS_VM_NEEDS_CALLBACK: string;
    STATUS_VM_CALLBACK_ATTEMPTED: string;
    STATUS_VM_CALLBACK_TOO_MANY_ATTEMPTS: string;
    STATUS_WRONG_NUMBER: string;
    STATUS_INCOMPLETE: string;
    STATUS_NON_PROSPECT: string;
    STATUS_FOLLOWUP_SET_APPT: string;
    STATUS_FOLLOWUP_APPT_REQUEST_FORM: string;
    STATUS_FOLLOWUP_NO_ANSWER: string;
    STATUS_APPT_SET: string;
    STATUS_TENTATIVE_APPT: string;
    STATUS_MISSED_OPPORTUNITY: string;
    STATUS_MO_NO_ANSWER: string;
    STATUS_NEW: string;
    STATUS_QUICK_PICK_REFUSED_NAME_ADDRESS: string;
    STATUS_QUICK_PICK_CALLER_REFUSED_HELP: string;
    MAX_CLINIC_FOLLOWUP_ATTEMPTS: number;
    MAX_PATIENT_FOLLOWUP_ATTEMPTS: number;
    MAX_VM_OUTBOUND_ATTEMPTS: number;
    easternTimezone: string;
    DIRECT_BOOK_NONE: string;
    DIRECT_BOOK_DM: string;
    DIRECT_BOOK_BLUEPRINT: string;
    DIRECT_BOOK_EARQ: string;
    IS_CLINIC_LOOKUP_PAGE?: boolean;
    IS_CALL_GROUP_EDIT_PAGE?: boolean;
}

// Make these available as global variables
declare const PROSPECT_YES: string;
declare const PROSPECT_NO: string;
declare const PROSPECT_UNKNOWN: string;
declare const PROSPECT_DISCONNECTED: string;
declare const prospectTopics: Record<string, string>;
declare const SCORE_APPT_SET: string;
declare const SCORE_TENTATIVE_APPT: string;
declare const SCORE_APPT_SET_DIRECT: string;
declare const SCORE_NOT_REACHED: string;
declare const SCORE_MISSED_OPPORTUNITY: string;
declare const SCORE_DISCONNECTED: string;
declare const callTypes: Record<string, string>;
declare const CALL_TYPE_INBOUND: string;
declare const CALL_TYPE_INBOUND_QUICK_PICK: string;
declare const CALL_TYPE_VM_CALLBACK_CLINIC: string;
declare const CALL_TYPE_VM_CALLBACK_CONSUMER: string;
declare const CALL_TYPE_VM_CALLBACK_INVALID: string;
declare const CALL_TYPE_FOLLOWUP_APPT_REQUEST: string;
declare const CALL_TYPE_FOLLOWUP_APPT_REQUEST_DIRECT: string;
declare const CALL_TYPE_FOLLOWUP_APPT: string;
declare const CALL_TYPE_FOLLOWUP_NO_ANSWER: string;
declare const CALL_TYPE_FOLLOWUP_TENTATIVE_APPT: string;
declare const statuses: Record<string, string>;
declare const STATUS_VM_NEEDS_CALLBACK: string;
declare const STATUS_VM_CALLBACK_ATTEMPTED: string;
declare const STATUS_VM_CALLBACK_TOO_MANY_ATTEMPTS: string;
declare const STATUS_WRONG_NUMBER: string;
declare const STATUS_INCOMPLETE: string;
declare const STATUS_NON_PROSPECT: string;
declare const STATUS_FOLLOWUP_SET_APPT: string;
declare const STATUS_FOLLOWUP_APPT_REQUEST_FORM: string;
declare const STATUS_FOLLOWUP_NO_ANSWER: string;
declare const STATUS_APPT_SET: string;
declare const STATUS_TENTATIVE_APPT: string;
declare const STATUS_MISSED_OPPORTUNITY: string;
declare const STATUS_MO_NO_ANSWER: string;
declare const STATUS_NEW: string;
declare const STATUS_QUICK_PICK_REFUSED_NAME_ADDRESS: string;
declare const STATUS_QUICK_PICK_CALLER_REFUSED_HELP: string;
declare const MAX_CLINIC_FOLLOWUP_ATTEMPTS: number;
declare const MAX_PATIENT_FOLLOWUP_ATTEMPTS: number;
declare const MAX_VM_OUTBOUND_ATTEMPTS: number;
declare const easternTimezone: string;
declare const DIRECT_BOOK_NONE: string;
declare const DIRECT_BOOK_DM: string;
declare const DIRECT_BOOK_BLUEPRINT: string;
declare const DIRECT_BOOK_EARQ: string;

// For Bootstrap modal
declare const bootstrap: any;